spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:mysql://localhost:3306/football_ticketing
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: ${datasource-password}